### ISSUE TITLE
GDPR

### ISSUE THREAD

**Issue by JohnRSim** [apertureless/vue-cookie-law#32]
Are there any plans to support the new cookie law being applied 25th May?
https://www.cookielaw.org/blog/2016/5/13/the-gdpr,-cookie-consent-and-customer-centric-privacy/

**Comment by apertureless** [comment]
Hey @JohnRSim 

to be honest, I don't really know. I would love to keep up to the law specifications. 
However it is not that easy. As the settings would change per site. Because every site has different settings, different cookies etc. 

So I have to figure out a good possibility to make it configureable.

**Comment by JohnRSim** [comment]
Additionally I came across this site  - which I think covers a lot of what is needed and they have a nice clean UI for both desktop and mobile.

https://uk.westfield.com/london

**Comment by apertureless** [comment]
Oh yeah, they are using the OneTrust solution, like many sites. (mailchimp for example)

I will need to read the law more carefully and see what is required and how to implement it.
